services:
    ger.modbreak.listener:
        class: ger\modbreak\event\main_listener
        arguments:
            - '@auth'
            - '@request'
            - '@user'
            - '%core.php_ext%' 
            - '@language'
            - '@template'
        tags:
            - { name: event.listener }
